#!/usr/bin/env python3
"""Generate the app-icon artwork: a branching crack, as tapering filled polygons.

WHY GENERATED AND NOT HAND-DRAWN, in three iterations' worth of reasons.

  Round-capped strokes of uniform width read as a MOLECULAR DIAGRAM. Round caps turn every
  branch end into a knob and a constant width reads as a line someone drew. A crack has a
  wide mouth, an irregular width and a SHARP tip, and none of that is a plain stroke.

  Tapering polygons on a hand-placed 8-point centreline read as a LIGHTNING BOLT. Few
  vertices with large direction changes is exactly what a bolt is. A crack deviates often
  and slightly -- it is following a microstructure, not discharging -- so the centreline is
  generated by subdividing a straight run with high-frequency, low-amplitude wander.

  Branches at right angles read as THORNS. Real branches leave at a shallow angle, because
  they are driven by the same stress field as the trunk, so each one here departs on the
  trunk's own local direction rotated 26-42 degrees and keeps going.

Seeded, so the icon is byte-reproducible: an icon that changes every build is a diff nobody
can review.

Widths are set by the 16 px case. The artwork is 824 units inside a 1024 canvas, so at the
16 px icon size one screen pixel is about 64 units. The trunk's widest half-width is 52
(~1.6 px of total width at 16 px) and it is the only load-bearing mark there; the branches
are thinner on purpose and do their work from 32 px up.

    usage: make_icon_art.py > appicon.svg
"""
import math
import random
import sys

BODY = 824

#: The trunk's straight run, corner to corner. Everything else is derived from it.
A, B = (34, 796), (796, 28)

#: How many segments the trunk is subdivided into, and how far off the straight line each
#: joint may sit. 18 x 30 gives a path that deviates constantly and never far -- the
#: signature of a crack. Half that count at twice the amplitude is a bolt.
TRUNK_SEGMENTS = 18
TRUNK_WANDER = 30

#: Where along the trunk each branch leaves (0-1), which side (+1/-1), its angle off the
#: local trunk direction in degrees, its length, and its half-width at the junction.
BRANCHES = [
    (0.30, -1, 34, 250, 26),
    (0.55, +1, 30, 205, 23),
    (0.72, -1, 40, 165, 19),
    (0.14, +1, 38, 130, 16),
    (0.88, +1, 26, 120, 13),
    (0.44, -1, 42, 96, 12),
]


def _wander(a, b, n, amp, rng):
    """A straight run from a to b, subdivided, each interior joint pushed off the line.

    The amplitude is scaled by a sine over the run so the ends stay near a and b: without
    that the first and last joints wander too, and the crack no longer reaches the edges it
    was placed to reach.
    """
    ax, ay = a
    bx, by = b
    dx, dy = bx - ax, by - ay
    L = math.hypot(dx, dy) or 1.0
    nx, ny = -dy / L, dx / L
    out = []
    for i in range(n + 1):
        t = i / n
        off = 0.0 if i in (0, n) else rng.uniform(-amp, amp) * math.sin(math.pi * t) ** 0.5
        out.append((ax + dx * t + nx * off, ay + dy * t + ny * off))
    return out


def _at(path, t):
    """Point and unit direction at fraction t along a polyline."""
    segs = [(path[i], path[i + 1]) for i in range(len(path) - 1)]
    lens = [math.dist(p, q) for p, q in segs]
    total = sum(lens)
    want = t * total
    run = 0.0
    for (p, q), L in zip(segs, lens):
        if run + L >= want or (p, q) == segs[-1]:
            u = (want - run) / (L or 1.0)
            d = ((q[0] - p[0]) / (L or 1.0), (q[1] - p[1]) / (L or 1.0))
            return (p[0] + (q[0] - p[0]) * u, p[1] + (q[1] - p[1]) * u), d
        run += L
    return path[-1], (0.0, 0.0)


def _polygon(pts, w0, w1, rng, wobble=0.18):
    """Close a centreline into a tapering polygon with an irregular edge.

    The two edges get INDEPENDENT wobble. Offsetting both by the same jitter only moves the
    centreline and leaves the width perfectly smooth, which is the thing being fixed.
    """
    n = len(pts)
    norms = []
    for i in range(n):
        a = pts[max(i - 1, 0)]
        b = pts[min(i + 1, n - 1)]
        dx, dy = b[0] - a[0], b[1] - a[1]
        L = math.hypot(dx, dy) or 1.0
        norms.append((-dy / L, dx / L))

    left, right = [], []
    for i, (x, y) in enumerate(pts):
        t = i / (n - 1)
        # Cosine taper, not linear: a linear taper is a wedge, and a crack holds most of
        # its width through the middle and then closes over the last short stretch.
        w = w1 + (w0 - w1) * (0.5 + 0.5 * math.cos(math.pi * t)) ** 0.75
        nx, ny = norms[i]
        left.append((x + nx * w * (1 + rng.uniform(-wobble, wobble)),
                     y + ny * w * (1 + rng.uniform(-wobble, wobble))))
        right.append((x - nx * w * (1 + rng.uniform(-wobble, wobble)),
                      y - ny * w * (1 + rng.uniform(-wobble, wobble))))

    ring = left + right[::-1]
    return "M" + " L".join(f"{px:.1f} {py:.1f}" for px, py in ring) + " Z"


def main():
    rng = random.Random(11)
    trunk_c = _wander(A, B, TRUNK_SEGMENTS, TRUNK_WANDER, rng)
    trunk = _polygon(trunk_c, 52, 15, rng)

    branches = []
    for t, side, deg, length, w in BRANCHES:
        (px, py), (dx, dy) = _at(trunk_c, t)
        th = math.radians(deg) * side
        ux = dx * math.cos(th) - dy * math.sin(th)
        uy = dx * math.sin(th) + dy * math.cos(th)
        # Start a little back inside the trunk so the junction is filled, not butted.
        start = (px - ux * w * 0.6, py - uy * w * 0.6)
        end = (start[0] + ux * length, start[1] + uy * length)
        pts = _wander(start, end, 7, length * 0.09, rng)
        branches.append(_polygon(pts, w, 0, rng))

    nl = chr(10)
    print(f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by packaging/make_icon_art.py (seed 11). Edit that, not this. -->
<svg xmlns="http://www.w3.org/2000/svg" width="{BODY}" height="{BODY}" viewBox="0 0 {BODY} {BODY}">
  <defs>
    <linearGradient id="field" x1="0" y1="0" x2="0.55" y2="1">
      <stop offset="0" stop-color="#2b3037"/>
      <stop offset="0.52" stop-color="#1c2026"/>
      <stop offset="1" stop-color="#11141a"/>
    </linearGradient>
    <radialGradient id="sheen" cx="0.26" cy="0.16" r="0.78">
      <stop offset="0" stop-color="#8ea0b4" stop-opacity="0.24"/>
      <stop offset="1" stop-color="#8ea0b4" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="crack" x1="0.08" y1="1" x2="0.92" y2="0">
      <stop offset="0" stop-color="#3f8ada"/>
      <stop offset="0.42" stop-color="#9fd2ff"/>
      <stop offset="1" stop-color="#ffffff"/>
    </linearGradient>
    <filter id="bloom" x="-25%" y="-25%" width="150%" height="150%">
      <feGaussianBlur stdDeviation="20"/>
    </filter>
  </defs>

  <!-- FULL BLEED: transparent corners are the loudest way an icon reads as broken, and
       they look fine on a white editor background. -->
  <rect width="{BODY}" height="{BODY}" fill="url(#field)"/>
  <rect width="{BODY}" height="{BODY}" fill="url(#sheen)"/>

  <!-- A bloom under the crack so the bright fill sits IN the metal, not on top of it. -->
  <g filter="url(#bloom)" opacity="0.5" fill="#2a78d6">
    <path d="{trunk}"/>
{nl.join(f'    <path d="{b}"/>' for b in branches)}
  </g>

  <!-- Branches under the trunk, so the trunk covers the joints: a branch drawn OVER the
       trunk reads as a second crack crossing it. -->
  <g fill="url(#crack)">
{nl.join(f'    <path d="{b}"/>' for b in branches)}
    <path d="{trunk}"/>
  </g>
</svg>''')


if __name__ == "__main__":
    main()
